# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48949d2af3518a70f79852d136943aa8a127037992df1a9831658baa18fc3577ea3bb540c536a2a1c512524ca21b761e378438ef8dafd4bc943ca0058a0d0b87

test:
  secret_key_base: 67535a5224f37bcd0686da55c5e67431a1dc82e3718fdeda422394493b91cdb9122384c13df99df34cb3da3c3f7c6ae825cefe01dcab0845de019bf668439889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
